### ISSUE TITLE
Unable to search for tags with colon or 2+ periods

### ISSUE THREAD

**Issue by tehoko** [rr-/szurubooru#97] opened 2016-09-26 18:57 UTC
Searching for certain tags returns an error, and only editing the URL manually allows accessing the tag.

`>:)`
*Unknown named token: ‘>’. Available named tokens: [‘category’, ‘creation-date’,* (...)

`when_you_see_it...`
*Composite token when_you_see_it… is invalid in this context.*

**Comment by rr-** [comment] 2016-09-26 19:51
>and only editing the URL manually allows accessing the tag.

? full scenario please

**Comment by tehoko** [comment] 2016-09-26 20:18
Right, that wording was less than ideal, sorry.

I meant that I couldn't find the tag `when_you_see_it...` and had to search for `when_you_see_it` (note no ellipsis), which is the former's alias. Then I added the ellipsis to the URL and could access the tag.

I didn't know I can use `*` to search with wildcards - adding `*` at the end solves the searching problem.

**Comment by rr-** [comment] 2016-09-26 20:27
>Searching for certain tags returns an error, and only editing the URL manually allows accessing the tag.

>`>:)`
>*Unknown named token: ‘>’. Available named tokens: [‘category’, ‘creation-date’,* (...)

Partially fixed, see comment below

>`when_you_see_it...`
>*Composite token when_you_see_it… is invalid in this context.*

Fixed, see comment below

The comment:

1. The user can now use `..` in string criteria (`user:great..dude`, `puella_magi_great..dude`). `date:yesterday..today` still works as intended.
2. The user can search for `>:)`. Only `[a-z-]+` will get treated as named token.
3. I don't want to fallback to default search for unknown named tokens to anonymous tokens. Let's compare what happens if I do that with what happens if I don't:

   1. `unknown:blabla` throws errors
        1. I type `re:zero` and get an error about invalid search. It's useless.
        2. I type `scoremin:whatever` and get an error about invalid search. It's useful and informs me I should use `score` instead.
    2. `unknown:blabla` doesn't throw errors
        1. I type `re:zero` and don't get errors. I get images for `re:zero`.
        2. I type `scoremin:whatever` and get no results. I don't know if it's my input's fault or if there are no images tagged with `re:zero` or even if there is such tag.

4. I decided to go with 2. because it's the lesser evil, and at the same time, you still can search for images tagged with `re:zero` with `re*zero` *and* `re\:zero` (since `re\` it doesn't match `[a-z-]+`).

This leads to further possible improvements that are not live yet:

1. If user inputs bad tag, show a message that the tag doesn't exist rather than the `no data to show` dialog.
2. When the user chooses a tag from autocomplete, escape `:` with `\`.

Let me know what you think.

**Comment by tehoko** [comment] 2016-09-29 17:20
Both possible improvements are great.

How about going with 3.ii., but apart from displaying `No data to show` also display the list of special tokens if the input contains `:`? This could solve the "I don't know if it's my input's fault" problem.

**Comment by rr-** [comment] 2016-09-29 17:49
>How about going with 3.ii., but apart from displaying No data to show also display the list of special tokens if the input contains :? This could solve the "I don't know if it's my input's fault" problem.

I don't like this, it feels too magic

**Comment by rr-** [comment] 2016-09-29 20:52
Implemented escaping `:` in https://github.com/rr-/szurubooru/commit/977cc47966f4b9dfddf62e53d9c614593fd29f7f (it tries to be smart: it escapes `re:zero`, but doesn't escape `:D`)

>If user inputs bad tag, show a message that the tag doesn't exist rather than the no data to show dialog.

Hmm. I checked things out and this requires quite boilerplate, and will reduce speed of *every* query including valid ones; do we still want this?

**Comment by tehoko** [comment] 2016-10-01 16:27
Depends what's the difference, since nobody will notice if it's taking 20 ms instead of 10 ms.

I haven't given that suggestion too much thought, though. What would the user gain if it showed that a tag doesn't exist? Would this only be useful for multi-tag queries?

**Comment by rr-** [comment] 2016-10-01 16:32
No idea, I say screw it until someone needs it

**Comment by rr-** [comment] 2016-10-08 17:54
Closing because tehoko reacted with thumbs up emoji

**Closed by rr-** 2016-10-08 17:54 UTC
