### ISSUE TITLE
Reddit users links doesn't display correctly in the tag description on the "Summary" tab.

### ISSUE THREAD

**Issue by hujle** [rr-/szurubooru#428] opened 2021-08-08 11:02 UTC
I'm not sure that's how it's supposed to work.
![image](https://user-images.githubusercontent.com/16465620/128629778-089940b6-cfad-42c2-ab05-34d870611063.gif)

**Comment by neobooru** [comment] 2021-08-08 15:50
Yeah the markdown handling is a bit weird imo, see #415 for more.
I wouldn't even know how to fix this, because this is 'expected behavior', though imo it has more cons than pros.

I suppose a workaround for now would be to use `https://reddit.com//user/graveyardcat` which seems to work, and the link still resolves to the same thing.

I am going to close this issue, please redirect all discussion/other problems to the issue linked above (which will stay open).

**Closed by neobooru** 2021-08-08 15:50 UTC
