### ISSUE TITLE
Tagnames with / throw error "Cannot read property ‘version’ of null"

### ISSUE THREAD

**Issue by Virepri** [rr-/szurubooru#312] opened 2020-04-05 04:11 UTC
In my case, these tags are:
`board:/biz/`
and
`board:/g/`

Both of these, when attempting to mass tag with them, return this. They also return this when I directly look at the tag (in attempt to delete it in favor of `board:biz`)

**Comment by sgsunder** [comment] 2020-04-05 19:54
Hmm, I can't reproduce this. 

1) Did you change these config parameters from the defaults?
```
tag_name_regex: ^\S+$
tag_category_name_regex: ^[^\s%+#/]+$
```

2) Looking at the error message it seems like a client-side JS issue. Looks like it's trying to fetch the `version` property of some object that unexpectedly got set to `null`. So this might be related to how the browser is escaping the forward-slash in the GET request. A poorly formatted request to the API might have led to a null response. Do you know what browser this error shows up on? I tested on both Google Chrome v80 and Safari 13.0.5 (didn't get a chance to test Firefox yet, and I don't have access to a Windows machine that can run IE at the moment).

**Comment by Virepri** [comment] 2020-04-05 20:18
I am actively reproducing on Vivaldi 2.8.1664.44 (Stable channel) (64-bit).

**Comment by Virepri** [comment] 2020-04-05 20:19
I could capture some fiddler traces, if you wish.

**Comment by sgsunder** [comment] 2020-04-06 16:33
This is how Chrome v80 escapes the URLs for me, can you confirm if yours looks similar?
<img width="1312" alt="Screen Shot 2020-04-06 at 12 29 54 PM" src="https://user-images.githubusercontent.com/16943235/78581875-74056600-7802-11ea-92b9-df9790bc338e.png">

**Comment by sgsunder** [comment] 2020-06-05 01:33
Closing for now, unless I (or someone) can show how to replicate this.

**Closed by sgsunder** 2020-06-05 01:33 UTC
Labels: bug
