### ISSUE TITLE
Start szurubooru fails with KeyError: 'path' and AttributeError: 'Hit' object has no attribute 'path' and elasticsearch.exceptions.RequestError

### ISSUE THREAD

**Issue by Darksonn** [rr-/szurubooru#117] opened 2017-02-02 08:28 UTC
I've installed szurubooru by following the instructions, while adapting them for debian.

I managed to start the server once, but uploading images failed with "Internal Server Error".

I then later closed the server and restarted it, and now it wont start, and it gives the following error message:

    [2017-02-02 09:19:29 +0100] [12400] [INFO] Starting gunicorn 19.6.0
    [2017-02-02 09:19:29 +0100] [12400] [INFO] Listening at: http://127.0.0.1:6666 (12400)
    [2017-02-02 09:19:29 +0100] [12400] [INFO] Using worker: sync
    [2017-02-02 09:19:29 +0100] [12403] [INFO] Booting worker with pid: 12403
    [2017-02-02 09:19:30] elasticsearch GET http://localhost:9200/szurubooru/image/_search?scroll=5m&size=1000 [status:200 request:0.005s]
    [2017-02-02 09:19:30 +0100] [12403] [ERROR] Exception in worker process
    Traceback (most recent call last):
      File "/home/szuru/.python/lib/python3.5/site-packages/elasticsearch_dsl/utils.py", line 112, in __getattr__
        return self.__getitem__(attr_name)
      File "/home/szuru/.python/lib/python3.5/site-packages/elasticsearch_dsl/utils.py", line 125, in __getitem__
        return _wrap(self._d_[key])
    KeyError: 'path'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/szuru/.python/lib/python3.5/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
        worker.init_process()
      File "/home/szuru/.python/lib/python3.5/site-packages/gunicorn/workers/base.py", line 126, in init_process
        self.load_wsgi()
      File "/home/szuru/.python/lib/python3.5/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
        self.wsgi = self.app.wsgi()
      File "/home/szuru/.python/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
        self.callable = self.load()
      File "/home/szuru/.python/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
        return self.load_wsgiapp()
      File "/home/szuru/.python/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
        return util.import_app(self.app_uri)
      File "/home/szuru/.python/lib/python3.5/site-packages/gunicorn/util.py", line 357, in import_app
        __import__(module)
      File "/home/szuru/szuru/server/szurubooru/facade.py", line 118, in <module>
        app = create_app()
      File "/home/szuru/szuru/server/szurubooru/facade.py", line 105, in create_app
        posts.populate_reverse_search()
      File "/home/szuru/szuru/server/szurubooru/func/posts.py", line 561, in populate_reverse_search
        excluded_post_ids = image_hash.get_all_paths()
      File "/home/szuru/szuru/server/szurubooru/func/image_hash.py", line 68, in get_all_paths
        return set(h.path for h in search.scan())
      File "/home/szuru/szuru/server/szurubooru/func/image_hash.py", line 68, in <genexpr>
        return set(h.path for h in search.scan())
      File "/home/szuru/.python/lib/python3.5/site-packages/elasticsearch_dsl/utils.py", line 115, in __getattr__
        '%r object has no attribute %r' % (self.__class__.__name__, attr_name))
    AttributeError: 'Hit' object has no attribute 'path'
    [2017-02-02 09:19:30 +0100] [12403] [INFO] Worker exiting (pid: 12403)
    [2017-02-02 09:19:30] elasticsearch DELETE http://localhost:9200/_search/scroll [status:400 request:0.001s]
    Exception ignored in: <generator object scan at 0x76e08065ca40>
    Traceback (most recent call last):
      File "/home/szuru/.python/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 324, in scan
        client.clear_scroll(body={'scroll_id': [scroll_id]}, ignore=(404, ))
      File "/home/szuru/.python/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 71, in _wrapped
        return func(*args, params=params, **kwargs)
      File "/home/szuru/.python/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 976, in clear_scroll
        params=params, body=body)
      File "/home/szuru/.python/lib/python3.5/site-packages/elasticsearch/transport.py", line 318, in perform_request
        status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
      File "/home/szuru/.python/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 127, in perform_request
        self._raise_error(response.status, raw_data)
      File "/home/szuru/.python/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 122, in _raise_error
        raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
    elasticsearch.exceptions.RequestError: [2017-02-02 09:19:30 +0100] [12400] [INFO] Shutting down: Master
    [2017-02-02 09:19:30 +0100] [12400] [INFO] Reason: Worker failed to boot.

The server runs debian stable. The python version is 3.5.1 (compiled from source).

**Comment by rr-** [comment] 2017-02-02 08:36
At a first glance looks like outdated elasticsearch package.

```shell
(python_modules) rr-@cyclone:/srv/www/yume.pl/server$ pip list|grep ela
elasticsearch (5.0.1)
elasticsearch-dsl (5.0.0)
(python_modules) rr-@cyclone:/srv/www/yume.pl/server$ elasticsearch --version
Version: 5.1.2, Build: c8c4c16/2017-01-11T20:18:39.146Z, JVM: 1.8.0_112
```

**Comment by Darksonn** [comment] 2017-02-02 09:00
Well we have:

    boats:~$ pip3 list | grep ela
    elasticsearch (5.1.0)
    elasticsearch-dsl (5.1.0)

And, uhh, this command: `/usr/share/elasticsearch/bin/elasticsearch --version` doesn't ever finish. It just hangs forever.

**Comment by rr-** [comment] 2017-02-02 09:05
>And, uhh, this command: /usr/share/elasticsearch/bin/elasticsearch --version doesn't ever finish. It just hangs forever.

It's certainly weird and probably the reason why the server fails to stand up. Have you tried installing the newest version from [the source](https://github.com/elastic/elasticsearch)?

Also if it proves too troublesome I can make the `elasticsearch` dependency optional (the server configured that way would be no longer able to detect similar uploads though.)

**Comment by Darksonn** [comment] 2017-02-02 10:15
I'm building it, but it appears that it's going to take a very long time. I know for a fact, that there are several duplicate images in the collection that will be uploaded, so I will need elasticsearch.

**Comment by Darksonn** [comment] 2017-02-02 11:12
Okay so I installed elasticsearch and started it. The server starts.

However uploading images still fails. I get an Internal server error, and the server prints the following:

    [2017-02-02 12:08:54] elasticsearch GET http://localhost:9200/szurubooru/image/_search?scroll=5m&size=1000 [status:404 request:0.229s]
    /home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/sql/default_comparator.py:161: SAWarning: The IN-predicate on "post.id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
      'strategies for improved performance.' % expr)
    [2017-02-02 12:08:55] elasticsearch POST http://localhost:9200/szurubooru/image?refresh=false [status:201 request:1.401s]
    Serving on http://0.0.0.0:6666
    [2017-02-02 12:09:06] szurubooru.middleware.request_logger GET /info (user=None, queries=2)
    [2017-02-02 12:09:12] szurubooru.middleware.request_logger GET /user/alice (user=alice, queries=6)
    [2017-02-02 12:09:12] szurubooru.middleware.request_logger GET /info (user=alice, queries=2)
    [2017-02-02 12:09:52] szurubooru.middleware.request_logger POST /uploads (user=alice, queries=0)
    [2017-02-02 12:09:52] szurubooru.middleware.request_logger POST /posts/reverse-search (user=alice, queries=1)
    /home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/sql/default_comparator.py:161: SAWarning: The IN-predicate on "post.id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
      'strategies for improved performance.' % expr)
    [2017-02-02 12:09:54] elasticsearch POST http://localhost:9200/szurubooru/image/_delete_by_query [status:200 request:0.100s]
    [2017-02-02 12:09:54] waitress Exception when serving /posts
    Traceback (most recent call last):
      File "/home/szuru/szuru/server/szurubooru/rest/app.py", line 95, in application
        response = handler(ctx, match.groupdict())
      File "/home/szuru/szuru/server/szurubooru/api/post_api.py", line 55, in create_post
        ctx.session.flush()
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2139, in flush
        self._flush(objects)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2259, in _flush
        transaction.rollback(_capture_exception=True)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
        compat.reraise(exc_type, exc_value, exc_tb)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
        raise value
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2223, in _flush
        flush_context.execute()
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
        rec.execute(self)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
        uow
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 193, in save_obj
        update_version_id in states_to_update
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 1012, in _finalize_insert_update_commands
        mapper.dispatch.after_insert(mapper, connection, state)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
        fn(*args, **kw)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/events.py", line 616, in wrap
        fn(*arg, **kw)
      File "/home/szuru/szuru/server/szurubooru/func/posts.py", line 261, in _after_post_insert
        _sync_post_content(post)
      File "/home/szuru/szuru/server/szurubooru/func/posts.py", line 284, in _sync_post_content
        image_hash.add_image(post.post_id, content)
      File "/home/szuru/szuru/server/szurubooru/func/image_hash.py", line 25, in add_image
        session.add_image(path=path, img=image_content, bytestream=True)
      File "/home/szuru/.python/lib/python3.5/site-packages/image_match/signature_database_base.py", line 202, in add_image
        rec = make_record(path, self.gis, self.k, self.N, img=img, bytestream=bytestream, metadata=metadata)
      File "/home/szuru/.python/lib/python3.5/site-packages/image_match/signature_database_base.py", line 339, in make_record
        signature = gis.generate_signature(img, bytestream=bytestream)
      File "/home/szuru/.python/lib/python3.5/site-packages/image_match/goldberg.py", line 168, in generate_signature
        avg_grey = self.compute_mean_level(im_array, x_coords, y_coords, P=self.P)
      File "/home/szuru/.python/lib/python3.5/site-packages/image_match/goldberg.py", line 402, in compute_mean_level
        lower_y_lim:upper_y_lim])  # no smoothing here as in the paper
    TypeError: slice indices must be integers or None or have an __index__ method
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/szuru/.python/lib/python3.5/site-packages/waitress/channel.py", line 338, in service
        task.service()
      File "/home/szuru/.python/lib/python3.5/site-packages/waitress/task.py", line 169, in service
        self.execute()
      File "/home/szuru/.python/lib/python3.5/site-packages/waitress/task.py", line 399, in execute
        app_iter = self.channel.server.application(env, start_response)
      File "/home/szuru/szuru/server/szurubooru/rest/app.py", line 98, in application
        hook(ctx)
      File "/home/szuru/szuru/server/szurubooru/middleware/request_logger.py", line 20, in process_response
        ctx.user.name,
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
        return self.impl.get(instance_state(instance), dict_)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 579, in get
        value = state._load_expired(state, passive)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 592, in _load_expired
        self.manager.deferred_scalar_loader(self, toload)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 698, in load_scalar_attributes
        only_load_props=attribute_names)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 223, in load_on_ident
        return q.one()
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2749, in one
        ret = self.one_or_none()
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2719, in one_or_none
        ret = list(self)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2790, in __iter__
        return self._execute_and_instances(context)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2811, in _execute_and_instances
        close_with_result=True)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2820, in _get_bind_args
        **kw
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2802, in _connection_from_session
        conn = self.session.connection(**kw)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 966, in connection
        execution_options=execution_options)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 971, in _connection_for_bind
        engine, execution_options)
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
        self._assert_active()
      File "/home/szuru/.python/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
        % self._rollback_exception
    sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: slice indices must be integers or None or have an __index__ method

**Comment by rr-** [comment] 2017-02-02 11:31
Hmm can you show the image which triggers that exception? Thanks

**Comment by Darksonn** [comment] 2017-02-02 11:35
I've tried several images, and they all trigger it, but here's one: http://ryhl.xyz/179-CxTbBGAUoAE1HiP.jpg

**Comment by rr-** [comment] 2017-02-02 16:38
Can reproduce after `pip upgrade`; working on a fix

**Comment by rr-** [comment] 2017-02-02 16:41
I think this is the issue: https://github.com/ascribe/image-match/issues/57

**Comment by rr-** [comment] 2017-02-02 16:53
Since the fix is not yet available on PIP, you can use HEAD:

```
pip install git+https://github.com/ascribe/image-match.git@master --upgrade --no-deps
````

**Comment by kotcrab** [comment] 2017-02-02 17:08
I'm having same issue. After running above command now I'm getting different exception:

```
[2017-02-02 17:59:20] waitress Exception when serving /posts/reverse-search
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/usr/lib/python3.6/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/usr/lib/python3.6/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/var/www/szuru/server/szurubooru/rest/app.py", line 95, in application
    response = handler(ctx, match.groupdict())
  File "/var/www/szuru/server/szurubooru/api/post_api.py", line 223, in get_posts_by_image
    for lookalike in posts.search_by_image(content)
  File "/var/www/szuru/server/szurubooru/api/post_api.py", line 219, in <listcomp>
    {
  File "/var/www/szuru/server/szurubooru/func/posts.py", line 553, in search_by_image
    for result in image_hash.search_by_image(image_content):
  File "/var/www/szuru/server/szurubooru/func/image_hash.py", line 44, in search_by_image
    bytestream=True):
  File "/usr/lib/python3.6/site-packages/image_match/signature_database_base.py", line 268, in search_image
    l = self.search_single_record(transformed_record)
  File "/usr/lib/python3.6/site-packages/image_match/elasticsearch_driver.py", line 65, in search_single_record
    timeout=self.timeout)['hits']['hits']
  File "/usr/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 71, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 569, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/lib/python3.6/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 127, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 122, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index')
```

**Comment by rr-** [comment] 2017-02-02 17:17
@kotcrab have you by any chance disabled dynamic mappings in elastic search? https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-mapping.html

**Comment by kotcrab** [comment] 2017-02-02 17:23
Ok I fixed it myself. I just ran `curl -XPUT 'localhost:9200/szurubooru'` to create index.

**Comment by rr-** [comment] 2017-02-02 17:27
@kotcrab normally the index would create itself on its own, but after I implemented reverse image search API, I made each upload request send an obligatory query to that API... and when the query tries to use index that wasn't created yet, it gets this error.

I'm fixing this right now

**Comment by kotcrab** [comment] 2017-02-02 17:44
@rr- great. On a side note I also had problems with missing Python module `cairo`. Solved with `pacman -S cairo` though not sure if I messed something up during install or it's missing from `INSTALL.md`.

**Comment by rr-** [comment] 2017-02-02 17:46
@kotcrab already requested image match to drop it https://github.com/ascribe/image-match/issues/59

**Comment by Darksonn** [comment] 2017-02-02 18:10
okay so I updated the pip thing, and am now able to upload images.  
I can't edit the tags of an image though, I get this error:

    Traceback (most recent call last):
      File "/home/szuru/.python/lib/python3.5/site-packages/waitress/channel.py", line 338, in service
        task.service()
      File "/home/szuru/.python/lib/python3.5/site-packages/waitress/task.py", line 169, in service
        self.execute()
      File "/home/szuru/.python/lib/python3.5/site-packages/waitress/task.py", line 399, in execute
        app_iter = self.channel.server.application(env, start_response)
      File "/home/szuru/szuru/server/szurubooru/rest/app.py", line 95, in application
        response = handler(ctx, match.groupdict())
      File "/home/szuru/szuru/server/szurubooru/api/post_api.py", line 81, in update_post
        new_tags = posts.update_post_tags(post, ctx.get_param_as_list('tags'))
      File "/home/szuru/szuru/server/szurubooru/func/posts.py", line 367, in update_post_tags
        existing_tags, new_tags = tags.get_or_create_tags_by_names(tag_names)
      File "/home/szuru/szuru/server/szurubooru/func/tags.py", line 190, in get_or_create_tags_by_names
        implications=[])
      File "/home/szuru/szuru/server/szurubooru/func/tags.py", line 279, in create_tag
        update_tag_category_name(tag, category_name)
      File "/home/szuru/szuru/server/szurubooru/func/tags.py", line 287, in update_tag_category_name
        tag.category = tag_categories.get_category_by_name(category_name)
      File "/home/szuru/szuru/server/szurubooru/func/tag_categories.py", line 99, in get_category_by_name
        category = try_get_category_by_name(name, lock)
      File "/home/szuru/szuru/server/szurubooru/func/tag_categories.py", line 92, in try_get_category_by_name   
        .filter(sqlalchemy.func.lower(db.TagCategory.name) == name.lower())
    AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by kotcrab** [comment] 2017-02-02 18:21
@Darksonn yea, I just checked it, same issue here. For some reason there isn't any default tag category defined. Go to `Tags`>`Tag categories` and create one.

**Comment by rr-** [comment] 2017-02-02 19:29
- Fixed error handling for elastic search
- Fixed inability to upload images without having elastic search index created
- Fixed tag editing error when no categories were created yet
- Fixed a few things related to DB sessions
- Added migration that adds default tag category if there were no other tag categories added yet
- Added ability to start the server without elastic search (though you'll still need it to upload images)

**Comment by rr-** [comment] 2017-02-03 18:09
Closing as the original issue seems to have been solved. Regarding using git master of image-match, which wasn't reflected in `requirements.txt` - I'm thinking of merging it into szurubooru itself (along with heavy refactoring), so maybe this dependency will be no longer needed.

**Closed by rr-** 2017-02-03 18:09 UTC
